name: "Monitoring Suite"
description: "Complete observability stack"
category: monitoring
pricing:
  model: subscription
  tiers:
    - name: Starter
      price: $35/month
      features:
        - Up to 10 users
        - Community support
        - Basic features
    - name: Professional
      price: $179/month
      features:
        - Up to 100 users
        - Priority support
        - Advanced features
        - API access
    - name: Enterprise
      price: $895/month
      features:
        - Unlimited users
        - 24/7 dedicated support
        - All features
        - Custom integrations
        - On-premise deployment
screenshots:
  - path: docs/screenshots/dashboard.png
    caption: Main dashboard
  - path: docs/screenshots/features.png
    caption: Key features
support:
  email: support@blackroad.io
  docs: https://docs.blackroad.io
  issues: https://github.com/BlackRoad-OS/blackroad-os-prometheus/issues
links:
  website: https://blackroad.io
  documentation: https://docs.blackroad.io
  privacy: https://blackroad.io/privacy
  terms: https://blackroad.io/terms
